// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dmvnormArma
double dmvnormArma(arma::vec x, arma::vec mean, arma::mat sigma);
RcppExport SEXP _FCARfreq_dmvnormArma(SEXP xSEXP, SEXP meanSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvnormArma(x, mean, sigma));
    return rcpp_result_gen;
END_RCPP
}
// rtruncnormRcpp
double rtruncnormRcpp(int n, double a, double b, double mean, double sd);
RcppExport SEXP _FCARfreq_rtruncnormRcpp(SEXP nSEXP, SEXP aSEXP, SEXP bSEXP, SEXP meanSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(rtruncnormRcpp(n, a, b, mean, sd));
    return rcpp_result_gen;
END_RCPP
}
// varArma
arma::mat varArma(double tau, double rho, arma::mat Dv, arma::mat nbd_mat);
RcppExport SEXP _FCARfreq_varArma(SEXP tauSEXP, SEXP rhoSEXP, SEXP DvSEXP, SEXP nbd_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Dv(DvSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type nbd_mat(nbd_matSEXP);
    rcpp_result_gen = Rcpp::wrap(varArma(tau, rho, Dv, nbd_mat));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_y
arma::mat gibbs_y(int M, arma::mat y, List nbd_index, arma::vec num_nei, arma::vec true_alpha, double true_rho, arma::mat G);
RcppExport SEXP _FCARfreq_gibbs_y(SEXP MSEXP, SEXP ySEXP, SEXP nbd_indexSEXP, SEXP num_neiSEXP, SEXP true_alphaSEXP, SEXP true_rhoSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< List >::type nbd_index(nbd_indexSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type num_nei(num_neiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type true_alpha(true_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type true_rho(true_rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_y(M, y, nbd_index, num_nei, true_alpha, true_rho, G));
    return rcpp_result_gen;
END_RCPP
}
// log_mvn_prec
double log_mvn_prec(const arma::vec& x, const arma::mat& Q, arma::mat& cholQ);
RcppExport SEXP _FCARfreq_log_mvn_prec(SEXP xSEXP, SEXP QSEXP, SEXP cholQSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type cholQ(cholQSEXP);
    rcpp_result_gen = Rcpp::wrap(log_mvn_prec(x, Q, cholQ));
    return rcpp_result_gen;
END_RCPP
}
// estX_fun_k
List estX_fun_k(int M, arma::vec X, arma::mat Dv, arma::mat W, arma::vec initial, double S_tau, double S_rho, bool autotune);
RcppExport SEXP _FCARfreq_estX_fun_k(SEXP MSEXP, SEXP XSEXP, SEXP DvSEXP, SEXP WSEXP, SEXP initialSEXP, SEXP S_tauSEXP, SEXP S_rhoSEXP, SEXP autotuneSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Dv(DvSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< double >::type S_tau(S_tauSEXP);
    Rcpp::traits::input_parameter< double >::type S_rho(S_rhoSEXP);
    Rcpp::traits::input_parameter< bool >::type autotune(autotuneSEXP);
    rcpp_result_gen = Rcpp::wrap(estX_fun_k(M, X, Dv, W, initial, S_tau, S_rho, autotune));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_FCARfreq_dmvnormArma", (DL_FUNC) &_FCARfreq_dmvnormArma, 3},
    {"_FCARfreq_rtruncnormRcpp", (DL_FUNC) &_FCARfreq_rtruncnormRcpp, 5},
    {"_FCARfreq_varArma", (DL_FUNC) &_FCARfreq_varArma, 4},
    {"_FCARfreq_gibbs_y", (DL_FUNC) &_FCARfreq_gibbs_y, 7},
    {"_FCARfreq_log_mvn_prec", (DL_FUNC) &_FCARfreq_log_mvn_prec, 3},
    {"_FCARfreq_estX_fun_k", (DL_FUNC) &_FCARfreq_estX_fun_k, 8},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_FCARfreq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
