# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnormArma <- function(x, mean, sigma) {
    .Call(`_FCARfreq_dmvnormArma`, x, mean, sigma)
}

rtruncnormRcpp <- function(n, a, b, mean, sd) {
    .Call(`_FCARfreq_rtruncnormRcpp`, n, a, b, mean, sd)
}

varArma <- function(tau, rho, Dv, nbd_mat) {
    .Call(`_FCARfreq_varArma`, tau, rho, Dv, nbd_mat)
}

gibbs_y <- function(M, y, nbd_index, num_nei, true_alpha, true_rho, G) {
    .Call(`_FCARfreq_gibbs_y`, M, y, nbd_index, num_nei, true_alpha, true_rho, G)
}

log_mvn_prec <- function(x, Q, cholQ) {
    .Call(`_FCARfreq_log_mvn_prec`, x, Q, cholQ)
}

estX_fun_k <- function(M, X, Dv, W, initial, S_tau, S_rho, autotune) {
    .Call(`_FCARfreq_estX_fun_k`, M, X, Dv, W, initial, S_tau, S_rho, autotune)
}

